FROM node:9

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/ .bin:$PATH

COPY ./test-app/package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install react-scripts@1 -g --silent

CMD ["npm", "start"]